version: "3.2"

services:
  app:
    build: "./"
    depends_on:
      - "db"
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: "db"
      MYSQL_DB: "app"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "123456"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '123456'
